Remove update time text after manual update
audrasjb/wp-autoupdates pull request #43
Opened 2020-03-08 19:42 UTC by bookdude13

Fixes #28. 

Note that in #28 the issue disappeared after a refresh, since the page reloading set the text properly. I didn't think a page reload made sense after an update (especially since multiple updates may occur with bulk actions), so I added a jQuery hook. If there are coding standard changes, or a better place to put this, let me know and I can update it. I'm always ready to learn 😄

2020-03-10 22:01 UTC, audrasjb requested changes

2020-03-10 22:01 UTC, audrasjb commented on wp-autoupdates.php
> +Contributors: wordpressdotorg, audrasjb, whodunitagency, pbiron, xkon, karmatosed, mapk, bookdude13
Please don’t directly add your name to the contributors on the plugin header.
You can add your name on the readme.md file and I will take care your name is added to the props list of WordPress 5.5, but the plugin’s list of contributors is updated manually.

Thanks for your comprehension :)

2020-03-10 22:06 UTC, bookdude13 commented on wp-autoupdates.php
> +Contributors: wordpressdotorg, audrasjb, whodunitagency, pbiron, xkon, karmatosed, mapk, bookdude13
My bad, and understood :) I thought I saw something similar in a PR here, but must've been mistaken.

2020-03-10 22:20 UTC, audrasjb commented on wp-autoupdates.php
> +Contributors: wordpressdotorg, audrasjb, whodunitagency, pbiron, xkon, karmatosed, mapk, bookdude13
Thank you very much :)

2020-03-10 22:23 UTC, audrasjb submitted a review, later dismissed

2020-03-13 15:37 UTC, pbiron requested changes
The `</span>` should be output before the `<br />`.

2020-03-13 15:39 UTC, pbiron requested changes
Setting the text to the empty string works.   but I think it would be better to just remove the span (e.g., `plugin_auto_update_time_text.remove()`.

2020-03-14 06:59 UTC, bookdude13 commented
> it would be better to just remove the span

I agree, removed.

> The `</span>` should be output before the `<br />`.

If this happens then there is a gap between the auto-updates enabled text and the enable/disable link (see Hello Dolly):
![gap_with_br](https://user-images.githubusercontent.com/6414232/76676979-26ae2400-65c9-11ea-9ee1-803f963b2f37.PNG)

I could try to use other selectors to remove that `<br />` in the script separately, but in my eyes the `<br />` is part of the text I'm trying to select with the `<span>`. If that's just bad practice though let me know.

2020-03-14 15:08 UTC, pbiron commented
> If this happens then there is a gap between the auto-updates enabled text and the enable/disable link (see Hello Dolly):

You're right, my bad...I reviewed too quickly. 

@audrasjb I think this is good to go now.

2020-03-14 15:09 UTC, pbiron approved these changes

2020-03-14 22:23 UTC, audrasjb commented
Yeah, it's good to go. Thank you @bookdude13 👍

2020-03-14 22:23 UTC, merged